export default [
    {
      setOne: [
        "Lazy",
        "Smelly",
        "Ratchet",
        "Haggard",
        "Egg Headed",
        "Terrible",
        "Swampy",
        "Loony",
        "Sphincter",
        "Mouth-Breathing",
        "Spastic",
         "Rotten",
         "Dandruff",
         "Ballsack",
         "Giant Rancid",
         "Ass",
         "Shady",
         "Cock-eyed",
         "Dimp",
         "Ding Head",
         "Douche Nozzle",
         "Douche",
         "Turd",
         "Crap",
         "Arse",
       "Twat",
       ""

      ]
    },
    {
      setTwo: [
        "Shart",
        "Bag",
        "Lint Sniffer",
        "Deposit",
        "Bitch",
        "Fart",
        "Twint",
        "Prick",
        "Goblin",
        "Square",
         "Sneeze",
        "Canoe",
      "Turd",
      "Quack",
      "Bead",
        "Swipe",
        "Clown",
        "Spatula Licker",
        "Butler",
        "Flosser",
        "Hole",
        "Dent",
        "Donkey",
        "Wipe",
        "Dingbat",
        "Bat",
        "Rat",
        "Taint",
        "Dipshit",
        "Wad",
        "Wanker",
        "Blossom",
        "Fuck Boy",
        "Butcomb",
        "Can",
        "Wanker",
        "Dump",
        "Landwhale",
        "Lunkhead",
        "Snowflake"
      ]
    }
  ];
  